spring:
  application:
    name: homework

  # H2 DB 설정
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: lkj
    password:

  # H2 콘솔 설정
  h2:
    console:
      enabled: true

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT 설정
jwt:
  secret: mysecretkeymysecretkeymysecretkey1234567890
  expiration: 3600000